---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hydra.
--- DateTime: 2020-01-15 09:24
---

local addonName, L = ...


local function parse_agent_whisper(msg)
    local pattern = "agent (.+)"
    local ag_msg = string.match(msg, pattern)
    return ag_msg
end


function L.F.may_say_agent(msg, author)
    local parsed_msg = parse_agent_whisper(msg)
    if parsed_msg and L.F.player_is_admin(author) then
        L.F.queue_message("(代理人)"..parsed_msg)
        return true
    else
        return false
    end
end
