---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hydra.
--- DateTime: 2020-01-29 02:58
---


local addonName, L = ...

local frame = CreateFrame("Frame", nil, UIParent)

frame:SetWidth(10)
frame:SetHeight(10)
frame.texture = frame:CreateTexture(nil, "OVERLAY")
frame.texture:SetAllPoints(frame)
frame:SetPoint("TOPLEFT", UIParent, 0, 0)
frame.texture:SetColorTexture(1, 0, 0)
frame:Show()
