---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hydra.
--- DateTime: 2020-01-05 13:17
---

local addonName, L = ...
local water_name = L.items.water_name
local food_name = L.items.food_name

function L.F.get_water_count(identity)
  if identity then
    return GetItemCount(water_name)
  else
    return math.modf(GetItemCount(water_name)/20)
  end
end

function L.F.get_bread_count(identity)
  if identity then
    return GetItemCount(food_name)
  else
    return math.modf(GetItemCount(food_name)/20)
  end
end

function L.F.get_food_count(identity)
  return L.F.get_water_count(identity) + L.F.get_bread_count(identity)
end

function L.F.get_free_slots()
  local free_slots = 0
  for b = 0, 4 do
    free_slots = free_slots + GetContainerNumFreeSlots(b)
  end
  return free_slots
end

function L.F.delete_item_at(b, s)
  PickupContainerItem(b, s)
  DeleteCursorItem()
end
