---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hydra.
--- DateTime: 2020-01-29 02:58
---


local addonName, L = ...

local frame = CreateFrame("FRAME")
frame:RegisterEvent("CHAT_MSG_ADDON")

local function eventHandler(self, event, arg1, arg2, arg3, arg4)
    if L.F.is_inviter() then
        if event == "CHAT_MSG_ADDON" and arg1 == "ATF" then
            local message, author = arg2, arg4
            author = string.match(author, "([^-]+)")
            local cmd, msg = string.match(message, "(.-):(.+)")
            if cmd and msg then
                if cmd == "invite" then
                    L.F.invite_player(msg)
                elseif cmd == "/s" then
                    L.F.whisper_or_say(msg)
                elseif cmd == "/w" then
                    local to_player, m = string.match(msg, "(.-):(.+)")
                    L.F.whisper_or_say(m, to_player)
                end
            end
        end
    end
end

frame:SetScript("OnEvent", eventHandler)
