---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hydra.
--- DateTime: 2020-01-14 19:07
---

local addonName, L = ...


local function split(inputstr, sep)
    if sep == nil then
        sep = "."
    end
    local t = {}
    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
        table.insert(t, str)
    end
    return t
end


local function get_target_table(tbl, keys)
    local tbl_next = tbl
    for _, key in ipairs(keys) do
        if tbl_next[key] == nil then
            tbl_next[key] = {}
        end
        tbl_next = tbl_next[key]
    end
    return tbl_next
end


function L.F.merge_statistics_plus_table(key, tbl)
    local rec = split(key)
    local target_tbl = get_target_table(ATFStatistics, rec)
    for k, v in pairs(tbl) do
        if target_tbl[k] == nil then
            target_tbl[k] = v
        else
            target_tbl[k] = target_tbl[key] + v
        end
    end
end


function L.F.merge_statistics_plus_int(key, value)
    local rec = split(key)
    local k = rec[#rec]
    table.remove(rec, #rec)
    local target_tbl = get_target_table(ATFStatistics, rec)
    if target_tbl[k] == nil then
        target_tbl[k] = value
    else
        target_tbl[k] = target_tbl[key] + value
    end
end


function L.F.query_statistics(key)
    local rec = split(key)
    local target = get_target_table(rec)
    return target
end


function L.F.query_statistics_int(key)
    local rec = split(key)
    local k = rec[#rec]
    table.remove(rec, #rec)
    local target = get_target_table(rec)
    if target[k] == nil then
        target[k] = 0
    end
    return target[k]
end

