---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hydra.
--- DateTime: 2020-01-05 13:53
---

local addonName, L = ...

function L.F.feed(itemname, icount, count_min)
  local x = 0
  if count_min == nil then count_min = 1 end
  for b = 0, 4 do
    for s =1, 32 do
      local _, itemCount, _, _, _, _, link = GetContainerItemInfo(b, s)
      if link and link:find(itemname) and itemCount>=count_min and x < icount then
        UseContainerItem(b, s)
        x = x + 1
      end
    end
  end
end


function L.F.post_check_opposite_trade()
  local target_items = {} local table_cnt = 0
  for t_index = 1, 6 do
    local name, _, cnt = GetTradeTargetItemInfo(t_index)
    if name then
      if target_items[name] == nil then
        target_items[name] = 0
      end
      target_items[name] = target_items[name] + cnt
      table_cnt = table_cnt + 1
    end
  end

  if GetTargetTradeMoney() > 0 then
    target_items["Gold"] = GetTargetTradeMoney()
    table_cnt = table_cnt + 1
  end

  return target_items, table_cnt
end

function L.F.do_accept_trade()
  if TradeHighlightRecipient:IsShown() then
    AcceptTrade()
    return true
  end
  return false
end
