---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hydra.
--- DateTime: 2020-01-10 22:42
---

local addonName, L = ...


function L.F.start_trade_hook()
    if L.F.is_frontend() then
        L.F.append_trade_hook(L.trade_hooks.trade_stone)
        L.F.append_trade_hook(L.trade_hooks.enlarge)
        L.F.append_trade_hook(L.trade_hooks.trade_refill)
        L.F.append_trade_hook(L.trade_hooks.trade_low_level_food)
        L.F.append_trade_hook(L.trade_hooks.trade_food)
    elseif L.F.is_enlarger() then
        L.F.append_trade_hook(L.trade_hooks.enlarge)
        L.F.append_trade_hook(L.trade_hooks.backend_default)
    end
end

