---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hydra.
--- DateTime: 2020-01-05 13:13
---

local addonName, L = ...

function L.F.create_macro_button(button_name, macro_text)
  local cframe = CreateFrame("Button", button_name, UIParent, "SecureActionButtonTemplate");
--  cframe:RegisterForClicks("AnyUp");
  cframe:SetAttribute("type", "macro");
  cframe:SetAttribute("macrotext", macro_text);
  return cframe
end

function L.F.search_str_contains(s, tbl)
  for _, ss in pairs(tbl) do
    if s and string.lower(s):find(ss) then
      return true
    end
  end
  return false
end

function L.F.my_position()
  local mapID = C_Map.GetBestMapForUnit("player")
  local tempTable = C_Map.GetPlayerMapPosition(mapID, "player")
  local x, y = tempTable.x, tempTable.y
  return string.format("(%.1f,%.1f)", x * 100, y * 100)
end

function L.F.check_buff(buff_name, remain)
  local i = 1;
  if remain == nil then
    remain = 0
  end
  while true do
    local buff, _, _,   _, dur, ts = UnitBuff("player", i);
    if buff == nil then
      return false
    elseif buff == buff_name then
      local remaining = ts - GetTime()
      return remaining > remain
    end
    i = i + 1;
  end;
end
